name: weather_now
description: The weather application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.0
  dartz: ^0.9.2
  equatable: ^1.2.5
  get_it: ^5.0.1
  injectable: ^1.0.5
  flutter_bloc: ^6.0.6


  flutter:
    sdk: flutter


dev_dependencies:
  build_runner:
  pedantic: ^1.9.2
  freezed: ^0.12.2
  json_serializable: ^3.5.0
  injectable_generator: ^1.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.jpg
    - assets/icons/broken_clouds.svg
    - assets/icons/clear_sky.svg
    - assets/icons/few_clouds.svg
    - assets/icons/mist.svg
    - assets/icons/rain.svg
    - assets/icons/scattered_clouds.svg
    - assets/icons/shower_rain.svg
    - assets/icons/snow.svg
    - assets/icons/thunderstorm.svg
    - assets/images/broken_clouds.jpg
    - assets/images/clear_sky.jpg
    - assets/images/few_clouds.jpg
    - assets/images/mist.jpg
    - assets/images/rain.jpg
    - assets/images/scattered_clouds.jpg
    - assets/images/shower_rain.jpg
    - assets/images/snow.jpg
    - assets/images/thunderstorm.jpg
  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Heebo-Light.ttf
          weight: 300
        - asset: assets/fonts/Heebo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Heebo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Heebo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Heebo-Bold.ttf
          weight: 700
