name: weather_now
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

óversion: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Heebo
      fonts:
        - asset: fonts/Heebo-ExtraLight.ttf
          weight: 200
        - asset: fonts/Heebo-Light.ttf
          weight: 300
        - asset: fonts/Heebo-Regular.ttf
          weight: 400
        - asset: fonts/Heebo-Medium.ttf
          weight: 500
        - asset: fonts/Heebo-SemiBold.ttf
          weight: 600
        - asset: fonts/Heebo-Bold.ttf
          weight: 700
